apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "9"
  creationTimestamp: 2018-05-29T14:29:57Z
  generation: 13
  labels:
    app: pbt-baseline
  name: pbt-baseline
  namespace: default
  resourceVersion: "1587432"
  uid: c300f19f-634c-11e8-8a62-42010a80017b
spec:
  replicas: 20
  selector:
    matchLabels:
      app: pbt-baseline
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 100%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: pbt-baseline
    spec:
      containers:
      - command:
        - ./run-k8-baseline.sh
        env:
        - name: N_WORKERS
          value: "50"
        - name: MAX_LENGTH
          value: "4"
        - name: MAX_REPEATS
          value: "16"
        - name: RUN
          value: cloud-baseline-l4r8
        - name: AMQP_URL
          value: amqp://admin:secretpassword@one-rabbitmq.default.svc.cluster.local:5672
        image: gcr.io/octavian-181621/github-octavian-ai-genetic-curriculum
        imagePullPolicy: Always
        name: github-octavian-ai-genetic-curriculum
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      - args:
        - --election=pbt-leader-baseline
        - --http=localhost:4040
        image: gcr.io/google_containers/leader-elector:0.4
        imagePullPolicy: IfNotPresent
        name: leader-elector
        ports:
        - containerPort: 4040
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
