apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: 2018-05-18T16:43:14Z
  generation: 10
  labels:
    app: pbt
  name: pbt
  namespace: default
  resourceVersion: "382916"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/pbt
  uid: 8f31246e-5aba-11e8-aece-42010a8001bf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pbt
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 100%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: pbt
    spec:
      containers:
      - image: gcr.io/octavian-181621/github-octavian-ai-genetic-curriculum
        imagePullPolicy: Always
        name: github-octavian-ai-genetic-curriculum
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      - args:
        - --election=monolith-jobs
        - --http=localhost:4040
        image: gcr.io/google_containers/leader-elector:0.4
        imagePullPolicy: IfNotPresent
        name: leader-elector
        ports:
        - containerPort: 4040
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30