apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "6"
  creationTimestamp: 2018-05-17T20:38:47Z
  generation: 9
  labels:
    app: pbt
  name: pbt
  namespace: default
  resourceVersion: "123521"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/pbt
  uid: 4ca72a98-5a12-11e8-8721-42010a8a016f
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pbt
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: pbt
    spec:
      containers:
      - image: gcr.io/octavian-181621/github-octavian-ai-genetic-curriculum:master
        imagePullPolicy: IfNotPresent
        name: github-octavian-ai-genetic-curriculum
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      - args:
        - --election=monolith-jobs
        - --http=localhost:4040
        image: gcr.io/google_containers/leader-elector:0.4
        imagePullPolicy: IfNotPresent
        name: leader-elector
        ports:
        - containerPort: 4040
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30