apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: 2018-05-20T19:16:08Z
  generation: 1
  labels:
    app: pbt
  name: pbt-big
  namespace: default
  resourceVersion: "1720336"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/pbt-big
  uid: 4039acbe-5c62-11e8-ba28-42010a8000b8
spec:
  replicas: 20
  selector:
    matchLabels:
      app: pbt
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 100%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: pbt
    spec:
      containers:
      - env:
        - name: N_WORKERS
          value: "20"
        - name: RUN
          value: cloud-v14
        - name: AMQP_URL
          value: amqp://fndicfmj:qCj7dwrZrGuOlLYPMDsNW08OLEype9_Q@black-boar.rmq.cloudamqp.com/fndicfmj?heartbeat=0
        - name: MAX_LENGTH
          value: "5"
        - name: MAX_REPEATS
          value: "20"
        image: gcr.io/octavian-181621/github-octavian-ai-genetic-curriculum
        imagePullPolicy: Always
        name: github-octavian-ai-genetic-curriculum
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      - args:
        - --election=pbt-leader
        - --http=localhost:4040
        image: gcr.io/google_containers/leader-elector:0.4
        imagePullPolicy: IfNotPresent
        name: leader-elector
        ports:
        - containerPort: 4040
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30