apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "8"
  creationTimestamp: 2018-05-29T14:29:57Z

  labels:
    app: pbt-smoketest
  name: pbt-smoketest
  namespace: default

spec:
  replicas: 5
  selector:
    matchLabels:
      app: pbt-smoketest
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 100%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: pbt-smoketest
    spec:
      containers:
      - command:
        - ./run-k8.sh
        env:
        - name: N_WORKERS
          value: "3"
        - name: RUN
          value: cloud-smoketest-v0
        - name: AMQP_URL
          value: amqp://admin:secretpassword@one-rabbitmq.default.svc.cluster.local:5672
        - name: MAX_REPEATS
          value: "2"
        - name: MAX_LENGTH
          value: "1"
        - name: MICRO_STEP
          value: "100"
        - name: MACRO_STEP
          value: "3"
        image: gcr.io/octavian-181621/github-octavian-ai-genetic-curriculum
        imagePullPolicy: Always
        name: github-octavian-ai-genetic-curriculum
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      - args:
        - --election=pbt-leader-smoketest
        - --http=localhost:4040
        image: gcr.io/google_containers/leader-elector:0.4
        imagePullPolicy: IfNotPresent
        name: leader-elector
        ports:
        - containerPort: 4040
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 42
  conditions:
  - lastTransitionTime: 2018-05-29T14:29:57Z
    lastUpdateTime: 2018-05-29T14:29:57Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 11
  readyReplicas: 42
  replicas: 42
  updatedReplicas: 42
